# This was almost entirely generated by AI but, I wanted to learn more about make syntax
# So, I copied all the information here making sure I understood each of the things I am writing.
CC = gcc
CFLAGS = -Wall -g
LDLIBS = -lm

SRCS := $(wildcard *.c)

PROGS := $(SRCS:.c=)

all: $(PROGS)

%: %.c
	$(CC) $(CFLAGS) $< -o $@ $(LDLIBS)

clean:
	rm -f $(PROGS)

