# This was almost entirely generated by AI but, I wanted to learn more about make syntax
# So, I copied all the information here making sure I understood each of the things I am writing.
CC = gcc
CFLAGS = -Wall -g
LDLIBS = -lm

SRCS := $(wildcard *.c)
PROGS := $(SRCS:.c=)

.PHONY: all clean run

all: $(PROGS)

# Pattern rule to compile any .c into a binary
%: %.c
	$(CC) $(CFLAGS) $< -o $@ $(LDLIBS)

# Updated run target
run: $(PROG)
	@echo "--- Running and Timing: $(PROG) ---"
	sudo perf stat ./$(PROG)

clean:
	rm -f $(PROGS)
